version: '1.0'

services:
  # FastAPI 应用服务
  app:
    build:
      context: .  # 使用当前目录下的 Dockerfile 构建镜像
    ports:
      - "80:80"  # 将宿主机的 80 端口映射到容器的 80 端口
    environment:
      - DATABASE_URL=mysql+asyncmy://root:test-Trip123@db:3306/trip  # 数据库连接 URL
      - ENV=test  # 设置环境变量
    depends_on:
      - db  # 确保数据库服务先启动
    restart: always
 
  # MySQL 数据库服务
  db:
    image: mysql:8.0  # 使用官方 MySQL 8.0 镜像
    environment:
      MYSQL_ROOT_PASSWORD: test-Trip123  # 设置 root 用户密码
      MYSQL_DATABASE: trip  # 创建一个名为 trip 的数据库
    ports:
      - "3307:3306"  # 将宿主机的 3307 端口映射到容器的 3306 端口
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化 MySQL 数据
    restart: always

# 定义持久化卷
volumes:
  mysql_data: